In [2]:
import numpy as np



In [12]:
S0 = 10
B0 = 10
S1 = np.array((20,5))
B1 = np.array((11,11));

In [15]:
M0 = np.array((S0,B0)) # model economy initial 

M1 = np.array((S1,B1))

K = 14.5 # strike price of call option 

In [19]:
C1 = np.maximum(S1 - K,0); # uncertain pay of from stock  

In [21]:
M1 = M1.T

In [22]:
M1

array([[20, 11],
       [ 5, 11]])

In [26]:
phi = np.linalg.solve(M1,C1)
phi

array([ 0.36666667, -0.16666667])

array([ 0.36666667, -0.16666667])