In [1]:
# reinforcement learning 
# no need for large labels and features data to be given upfront
import os
import math
import random
import numpy as np 
import pandas as pd
from pylab import plt, mpl
import gym
plt.style.use('seaborn')
mpl.rcParams['savefig.dpi'] = 300
mpl.rcParams['font.family'] = 'serif'
np.set_printoptions(precision = 4, suppress = True)
os.environ['PYTHONHASHSEED'] = '0'



In [2]:
env = gym.make("CartPole-v0")

/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/gym/envs/registration.py:594: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  f"The environment {id} is out of date. You should consider "
/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is 

In [3]:
env.seed(100)
env.action_space.seed(100)

/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/gym/core.py:257: DeprecationWarning: WARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed)` instead.
  "Function `env.seed(seed)` is marked as deprecated and will be removed in the future. "


[100]

In [4]:
env.observation_space

Box([-4.8000e+00 -3.4028e+38 -4.1888e-01 -3.4028e+38], [4.8000e+00 3.4028e+38 4.1888e-01 3.4028e+38], (4,), float32)

In [5]:
# min and max values in the observation space
env.observation_space.low.astype(np.float16)
env.observation_space.high.astype(np.float16)


array([4.8  ,   inf, 0.419,   inf], dtype=float16)

In [6]:
state = env.reset()

In [7]:
state

array([ 0.0335,  0.0097, -0.0211, -0.0457], dtype=float32)

In [8]:
env.action_space

Discrete(2)

In [9]:
env.action_space.n

2

In [10]:
a = env.action_space.sample()

In [11]:
a

1

In [12]:
state, reward, done, info = env.step(a)

In [13]:
state

array([ 0.0337,  0.2051, -0.022 , -0.345 ], dtype=float32)

In [14]:
reward

1.0

In [15]:
done   #done would be = True if the pole falls down 

False

In [16]:
env.reset()
for e in range(1,200):
    a = env.action_space.sample()
    state, reward, done, info = env.step(a)
    print(f'step={e:2d} | state={state} | action={a} | reward={reward}')
    if done and (e+1)< 200:
        print('*** FAILED ***')
        break
        

step= 1 | state=[ 0.0476  0.2043  0.0298 -0.2424] | action=1 | reward=1.0
step= 2 | state=[0.0516 0.0088 0.025  0.0596] | action=0 | reward=1.0
step= 3 | state=[ 0.0518  0.2036  0.0262 -0.2251] | action=1 | reward=1.0
step= 4 | state=[0.0559 0.0081 0.0217 0.0757] | action=0 | reward=1.0
step= 5 | state=[ 0.0561 -0.1874  0.0232  0.3752] | action=0 | reward=1.0
step= 6 | state=[ 0.0523 -0.3828  0.0307  0.6751] | action=0 | reward=1.0
step= 7 | state=[ 0.0447 -0.5783  0.0442  0.9773] | action=0 | reward=1.0
step= 8 | state=[ 0.0331 -0.3838  0.0638  0.6988] | action=1 | reward=1.0
step= 9 | state=[ 0.0254 -0.1896  0.0777  0.4269] | action=1 | reward=1.0
step=10 | state=[0.0216 0.0043 0.0863 0.1596] | action=1 | reward=1.0
step=11 | state=[ 0.0217  0.1981  0.0895 -0.1046] | action=1 | reward=1.0
step=12 | state=[0.0257 0.0018 0.0874 0.2149] | action=0 | reward=1.0
step=13 | state=[ 0.0257  0.1956  0.0917 -0.049 ] | action=1 | reward=1.0
step=14 | state=[ 0.0296  0.3893  0.0907 -0.3114] | ac

In [17]:
done

True

In [18]:
np.random.seed(100)
weights = np.random.random(4) * 2 -1 
weights

array([ 0.0868, -0.4433, -0.151 ,  0.6896])

In [19]:
state = env.reset()

In [20]:
state

array([ 0.0188, -0.031 ,  0.0481, -0.0215], dtype=float32)

In [21]:
s = np.dot(state, weights)
s

-0.0067370952515455294

In [22]:
if s <0: 
    a = 0
else:
    a = 1
a

0

In [23]:
def run_episode(env,weights):
    state = env.reset()
    treward = 0
    for _ in range(200):
        s = np.dot(state, weights)
        a = 0 if s<0 else 1
        state, reward, done, info = env.step(a)
        treward += reward
        if done:
            break
    return treward
run_episode(env, weights)
        

116.0

In [24]:
# montecarlo simulation to test a large number of weights 

def set_seeds(seed = 100):
    random.seed(seed)
    np.random.seed(seed)
    env.seed(seed)
    

In [25]:
set_seeds()
num_episodes = 1000

besttreward = 0
for e in range(1,num_episodes + 1):
    weights = np.random.rand(4)*2 + 1 
    treward = run_episode(env,weights)
    if treward > besttreward:
        besttreward = treward
        bestweights = weights
    if treward == 200:
        print(f'SUCCESS | episode = {e}')
        break
    print(f'UPDATE | episode = {e}')

UPDATE | episode = 1
SUCCESS | episode = 2


In [26]:
weights

array([1.0094, 1.2431, 2.3415, 2.6517])

In [27]:
res = []
for _ in range(100):
    treward = run_episode(env,weights)
    res.append(treward)
res[:10]

[200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0]

In [28]:
# Neural Network Agent
import tensorflow as tf 
from keras.layers import Dense, Dropout 
from keras.models import Sequential
from keras.optimizers import adam, RMSprop
from sklearn.metrics import accuracy_score

/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/tensorflow_core/python/framework/dtypes.py:597: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object,
/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/tensorflow_core/python/framework/dtypes.py:605: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool,
/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/s

In [29]:
def set_seeds(seed = 100):
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    env.seed(seed)
    env.action_space.seed(100)


In [30]:
# exploration and exploitation 

class NNAgent:
    def __init__(self):
        self.max = 0
        self.scores = list()
        self.memory = list()
        self.model = self._build_model()
    def _build_model(self):
        model = Sequential()
        model.add(Dense(24, input_dim = 4, activation = 'relu'))
        model.add(Dense(1,activation = 'sigmoid'))
        model.compile(loss = 'binary_crossentropy', 
                      optimizer = RMSprop(lr = 0.001))
        return model
    def act(self,state):
        if random.random() <0.5:
            return env.action_space.sample()
        action = np.where(self.model.predict(
            state, batch_size = None)[0,0] > 0.5, 1, 0)
        return action
    def train_model(self, state, action):
        self.model.fit(state,np.array([action,]), 
                      epochs = 1, verbose = False)
    def learn(self, episodes):
        for e in range(1,episodes+1):
            state = env.reset()
            for _ in range(201):
                state = np.reshape(state,[1,4])
                action = self.act(state)
                next_state, reward, done, info = env.step(action)
                if done:
                    score = _ + 1
                    self.scores.append(score)
                    self.max = max(score, self.max)
                    break
                self.memory.append((state,action))
                self.train_model(state,action)
                state = next_state
        
        
        

In [31]:
set_seeds(100)
agent = NNAgent()

/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/gym/core.py:257: DeprecationWarning: WARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed)` instead.
  "Function `env.seed(seed)` is marked as deprecated and will be removed in the future. "
2023-01-26 10:08:18.269151: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-26 10:08:18.270060: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/keras/engine/training_utils.py:811: DeprecationWarning: Using or

In [32]:
episodes = 500


In [33]:
agent.learn(episodes)


/Users/ananth/miniconda3/envs/tensorflow_env/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:339: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if not isinstance(values, collections.Sequence):


In [34]:
sum(agent.scores)/ len(agent.scores)

13.296

In [37]:
f = np.array([m[0][0] for m in agent.memory])
f

array([[ 0.0335,  0.0097, -0.0211, -0.0457],
       [ 0.0337,  0.2051, -0.022 , -0.345 ],
       [ 0.0378,  0.4005, -0.0289, -0.6445],
       ...,
       [ 0.0992,  0.3943, -0.1196, -0.8131],
       [ 0.1071,  0.5908, -0.1358, -1.1408],
       [ 0.1189,  0.7874, -0.1587, -1.4728]], dtype=float32)

In [38]:
l = np.array([m[1] for m in agent.memory])
l

array([1, 1, 1, ..., 1, 1, 1])

In [39]:
accuracy_score(np.where(agent.model.predict(f)>0.5, 1, 0), l)

0.7612231620039037

In [40]:
# dql agent - q learning 
# ql learning takes into account immediate rewards and delayed rewards 

from collections import deque 
from keras.optimizers import Adam, RMSprop

In [44]:
class DQLAgent:
    def __init__(self, gamma = 0.95, hu = 24, opt = Adam, 
                lr = 0.001, finish = False):
        self.finish = finish
        self.epsilon = 1.0
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.gamma = gamma
        self.batch_size = 32
        self.max_treward = 0
        self.averages = list()
        self.memory = deque(maxlen = 2000)
        self.osn = env.observation_space.shape[0]
        self.model = self._build_model(hu,opt,lr)
    def _build_model(self,hu,opt,lr):
        model = Sequential()
        model.add(Dense(hu,input_dim = self.osn, 
                       activation = 'relu'))
        model.add(Dense(hu,activation = 'relu'))
        model.add(Dense(env.action_space.n, activation = 'linear'))
        model.compile(loss = 'mse', optimizer = opt(lr = lr))
        return model
    def act(self, state):
        if random.random() <= self.epsilon:
            return env.action_space.sample()
        action = self.model.predict(state)[0]
        return np.argmax(action)
    def replay(self):
        batch = random.sample(self.memory, self.batch_size)
        for state, action, reward, next_state, done in batch:
            if not done:
                reward += self.gamma * np.max(
                    self.model.predict(next_state)[0])
                target = self.model.predict(state)
                target[0,action] = reward
                self.model.fit(state, target, epochs=1, 
                              verbose = False)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay
    
    def learn(self,episodes):
        trewards = []
        for e in range(1,episodes+1):
            state = env.reset()
            state = np.reshape(state, [1, self.osn])
            for _ in range(5000):
                action = self.act(state)
                next_state, reward, done, info = env.step(action)
                next_state = np.reshape(next_state, 
                                        [1, self.osn])
                self.memory.append([state, action, reward, 
                                   next_state, done])
                state = next_state
                if done:
                    treward = _ + 1 
                    trewards.append(treward)
                    av = sum(trewards[-25:])/25
                    self.averages.append(av)
                    self.max_treward = max(self.max_treward, treward)
                    templ = 'episode: {:4d}/{} | treward: {:4d} | '
                
        
    